id: IBD006820
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T10:15:23+00:00'
last_modified: '2022-06-07T10:26:26.295029+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28261
  title: སུམ་རྟགས་ཀྱི་འགྲེལ་པ་ཨུཏྤ་ལ་ཡི་རྣ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2AA9:
      image_group_id: I1KG12874
      title: Volume 1 of sum rtags kyi 'grel pa ut+pa la yi rna rgyan/
      total_pages: 156
      order: 1
      base_file: 2AA9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
